"""CFO report: financial ROI with credible intervals."""
from __future__ import annotations

from datetime import date

import pandas as pd

from agent_mmm.report.renderer import fmt_currency, fmt_roas, save_report


def generate_cfo_report(
    spec,
    diagnostics: dict,
    contributions_df: pd.DataFrame,
    roas_df: pd.DataFrame,
) -> str:
    """Generate the CFO markdown report and write it to mmm-workspace/reports/cfo.md.

    Returns the rendered markdown string.
    """
    currency = getattr(spec, "currency", "ILS")
    company = getattr(spec, "company", "")
    target_type = spec.target.type
    value_per_unit = spec.target.value_per_unit

    total_spend = roas_df["spend_ils"].sum() if roas_df is not None and len(roas_df) > 0 else 0.0
    total_contrib = contributions_df["mean"].sum()
    blended_roas = total_contrib / total_spend if total_spend > 0 else 0.0

    conv = diagnostics.get("convergence", {})
    metrics = diagnostics.get("fit_metrics", {})
    r2 = metrics.get("in_sample_r2")

    hdi_col_low = [c for c in roas_df.columns if "hdi" in c and "low" in c] if roas_df is not None else []
    hdi_col_high = [c for c in roas_df.columns if "hdi" in c and "high" in c] if roas_df is not None else []

    lines = [
        "# CFO Financial ROI Report",
        f"**{company}** | Generated {date.today().isoformat()}",
        "",
        "## Portfolio Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total media spend | {fmt_currency(total_spend, currency, 0)} |",
        f"| Total incremental contribution | {fmt_currency(total_contrib, currency, 0)} |",
        f"| Blended ROAS | {blended_roas:.2f}x |",
    ]
    if r2 is not None:
        lines.append(f"| Model in-sample R² | {r2:.3f} |")
    lines.append("")

    # Per-channel ROI table
    if roas_df is not None and len(roas_df) > 0:
        if target_type == "revenue":
            lines += [
                "## Per-Channel ROAS",
                "",
                "| Channel | Spend | Contribution | ROAS | 89% CI |",
                "|---------|-------|--------------|------|--------|",
            ]
            roas_sorted = roas_df.sort_values("roas_mean", ascending=False)
            for _, row in roas_sorted.iterrows():
                ch = row["channel"].replace("_spend", "")
                lo = row[hdi_col_low[0]] if hdi_col_low else row["roas_mean"]
                hi = row[hdi_col_high[0]] if hdi_col_high else row["roas_mean"]
                lines.append(
                    f"| {ch} | {fmt_currency(row['spend_ils'], currency, 0)} "
                    f"| {fmt_currency(row['contribution_mean_ils'], currency, 0)} "
                    f"| {row['roas_mean']:.2f}x | {lo:.2f}x–{hi:.2f}x |"
                )
        else:
            lines += [
                "## Per-Channel Cost per Acquisition (CPA)",
                "",
                "| Channel | Spend | Incremental units | CPA |",
                "|---------|-------|-------------------|-----|",
            ]
            roas_sorted = roas_df.sort_values("roas_mean", ascending=False)
            for _, row in roas_sorted.iterrows():
                ch = row["channel"].replace("_spend", "")
                units = row.get("contribution_mean_ils", 0)
                cpa = row["spend_ils"] / units if units > 0 else float("inf")
                revenue_eq = ""
                if value_per_unit and value_per_unit > 1.0:
                    implied_roas = value_per_unit / cpa if cpa > 0 else 0.0
                    revenue_eq = f" (implied ROAS {implied_roas:.2f}x at {fmt_currency(value_per_unit, currency)})"
                lines.append(
                    f"| {ch} | {fmt_currency(row['spend_ils'], currency, 0)} "
                    f"| {units:,.0f} | {fmt_currency(cpa, currency, 2)}{revenue_eq} |"
                )
        lines.append("")

    # Sensitivity note
    lines += [
        "## Sensitivity Note",
        "ROAS estimates reflect *incremental* (marginal) attribution — not total platform ROAS. "
        "Uncertainty intervals (89% CI) capture model posterior uncertainty, not measurement noise.",
        "",
        "_Report generated by agent_mmm. All monetary values in " + currency + "._",
    ]

    content = "\n".join(lines)
    save_report("cfo", content)
    return content
