"""CMO report: plain-English channel attribution narrative."""
from __future__ import annotations

from datetime import date

import pandas as pd

from agent_mmm.report.renderer import fmt_currency, fmt_hdi, save_report


def generate_cmo_report(
    spec,
    diagnostics: dict,
    contributions_df: pd.DataFrame,
    roas_df: pd.DataFrame,
) -> str:
    """Generate the CMO markdown report and write it to mmm-workspace/reports/cmo.md.

    Returns the rendered markdown string.
    """
    currency = getattr(spec, "currency", "ILS")
    company = getattr(spec, "company", "")
    target_type = spec.target.type

    # Contribution share
    total_contrib = contributions_df["mean"].sum()
    contrib = contributions_df.copy()
    contrib["share_pct"] = (contrib["mean"] / total_contrib * 100).round(1) if total_contrib > 0 else 0.0
    contrib = contrib.sort_values("mean", ascending=False)

    # Convergence confidence
    conv = diagnostics.get("convergence", {})
    tier = conv.get("tier", "UNKNOWN")
    confidence = {"PASS": "High", "WARN": "Medium", "FAIL": "Low"}.get(tier, "Unknown")

    # Top / bottom channels
    top = contrib.iloc[0] if len(contrib) > 0 else None
    bottom = contrib.iloc[-1] if len(contrib) > 1 else None

    # Executive summary
    if target_type == "revenue":
        metric_label = f"incremental revenue ({currency})"
    else:
        metric_label = "incremental units"

    lines = [
        f"# CMO Marketing Effectiveness Report",
        f"**{company}** | Generated {date.today().isoformat()} | Confidence: **{confidence}**",
        "",
        "## Executive Summary",
    ]

    if top is not None:
        lines.append(
            f"Marketing contributed a total of {fmt_currency(total_contrib, currency, 0)} "
            f"in {metric_label} during the analysis period. "
            f"**{top['channel'].replace('_spend','')}** was the strongest performer "
            f"({top['share_pct']:.0f}% of media contribution)."
        )
    if bottom is not None:
        lines.append(
            f"**{bottom['channel'].replace('_spend','')}** delivered the lowest contribution "
            f"({bottom['share_pct']:.0f}%) and warrants review."
        )
    lines.append("")

    # Channel contribution table
    lines += [
        "## Channel Contributions",
        "",
        "| Channel | Incremental contribution | Share | 89% CI |",
        "|---------|--------------------------|-------|--------|",
    ]
    for _, row in contrib.iterrows():
        ch = row["channel"].replace("_spend", "")
        mean_fmt = fmt_currency(row["mean"], currency, 0)
        ci = f"{fmt_currency(row['hdi_low'], currency, 0)}–{fmt_currency(row['hdi_high'], currency, 0)}"
        lines.append(f"| {ch} | {mean_fmt} | {row['share_pct']:.1f}% | {ci} |")
    lines.append("")

    # ROAS summary
    if roas_df is not None and len(roas_df) > 0:
        hdi_col_low = [c for c in roas_df.columns if "hdi" in c and "low" in c]
        hdi_col_high = [c for c in roas_df.columns if "hdi" in c and "high" in c]
        lines += [
            "## Return on Ad Spend (ROAS)",
            "",
            "| Channel | ROAS | 89% CI |",
            "|---------|------|--------|",
        ]
        roas_sorted = roas_df.sort_values("roas_mean", ascending=False)
        for _, row in roas_sorted.iterrows():
            ch = row["channel"].replace("_spend", "")
            lo = row[hdi_col_low[0]] if hdi_col_low else row["roas_mean"]
            hi = row[hdi_col_high[0]] if hdi_col_high else row["roas_mean"]
            lines.append(f"| {ch} | {row['roas_mean']:.2f}x | {lo:.2f}x–{hi:.2f}x |")
        lines.append("")

    # Confidence note
    lines += [
        "## Model Confidence",
        f"Convergence tier: **{tier}**. "
        f"Results reliability is **{confidence.lower()}**.",
        "",
        "_Report generated by agent_mmm. All monetary values in " + currency + "._",
    ]

    content = "\n".join(lines)
    save_report("cmo", content)
    return content
