"""Data Science report: full diagnostics, convergence, overfit, prior pull."""
from __future__ import annotations

from datetime import date

import pandas as pd

from agent_mmm.report.renderer import save_report


def generate_ds_report(
    spec,
    diagnostics: dict,
    prior_pull_df: pd.DataFrame | None = None,
    overfit_result: dict | None = None,
) -> str:
    """Generate Data Science markdown report.

    Returns the rendered markdown string.
    """
    import pymc_marketing

    company = getattr(spec, "company", "")
    currency = getattr(spec, "currency", "ILS")

    conv = diagnostics.get("convergence", {})
    metrics = diagnostics.get("fit_metrics", {})

    lines = [
        "# Data Science Diagnostics Report",
        f"**{company}** | Generated {date.today().isoformat()}",
        f"pymc-marketing version: {pymc_marketing.__version__}",
        "",
        "## Model Specification",
        "",
        "| Parameter | Value |",
        "|-----------|-------|",
        f"| Channels | {', '.join(ch.name for ch in spec.channels)} |",
        f"| Target column | {spec.target.column} ({spec.target.type}) |",
        f"| Currency | {currency} |",
        f"| Fourier modes | {spec.fourier_order} |",
        f"| Sampler draws | {spec.sampler.draws} |",
        f"| Sampler tune | {spec.sampler.tune} |",
        f"| Sampler chains | {spec.sampler.chains} |",
        f"| target_accept | {spec.sampler.target_accept} |",
        f"| Random seed | {spec.sampler.random_seed} |",
    ]

    for ch in spec.channels:
        lines.append(f"| {ch.name} adstock | {ch.adstock} (l_max={ch.l_max}) |")
        lines.append(f"| {ch.name} saturation | {ch.saturation} |")

    lines += [
        "",
        "## Convergence Summary",
        "",
        f"Overall tier: **{conv.get('tier', 'UNKNOWN')}**",
        "",
        "| Metric | Value | Threshold |",
        "|--------|-------|-----------|",
    ]
    rhat = conv.get("rhat_max")
    ess_bulk = conv.get("ess_bulk_min")
    ess_tail = conv.get("ess_tail_min")
    divs = conv.get("divergences", 0)

    if rhat is not None:
        flag = "OK" if rhat < 1.05 else "FAIL"
        lines.append(f"| rhat_max | {rhat:.4f} [{flag}] | < 1.05 |")
    if ess_bulk is not None:
        flag = "OK" if ess_bulk >= 400 else "FAIL"
        lines.append(f"| ess_bulk_min | {ess_bulk:.0f} [{flag}] | >= 400 |")
    if ess_tail is not None:
        flag = "OK" if ess_tail >= 400 else "FAIL"
        lines.append(f"| ess_tail_min | {ess_tail:.0f} [{flag}] | >= 400 |")
    lines.append(f"| divergences | {divs} | 0 |")

    lines += [
        "",
        "## Fit Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]
    for k, v in metrics.items():
        if v is not None:
            lines.append(f"| {k} | {v:.4f} |")

    if overfit_result is not None:
        lines += [
            "",
            "## Overfit Analysis",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| In-sample R² | {overfit_result.get('in_sample_r2', 'N/A')} |",
            f"| CV R² | {overfit_result.get('cv_r2', 'N/A')} |",
            f"| Overfit gap | {overfit_result.get('gap', 'N/A')} |",
            f"| Overfit tier | {overfit_result.get('tier', 'N/A')} |",
        ]

    if prior_pull_df is not None and len(prior_pull_df) > 0:
        lines += [
            "",
            "## Prior Pull (posterior_std / prior_std)",
            "",
            "Values < 0.8 → data informed; > 1.0 → prior dominated (investigate).",
            "",
            "| Param | Label | Ratio | Flag |",
            "|-------|-------|-------|------|",
        ]
        for _, row in prior_pull_df.iterrows():
            lines.append(f"| {row['param']} | {row['label']} | {row['ratio']:.4f} | {row['flag']} |")

    lines += [
        "",
        "## Issues",
    ]
    issues = conv.get("issues", [])
    if issues:
        for issue in issues:
            lines.append(f"- {issue}")
    else:
        lines.append("- No convergence issues detected.")

    lines += [
        "",
        f"_Report generated by agent_mmm. Model region: {spec.region}._",
    ]

    content = "\n".join(lines)
    save_report("ds", content)
    return content
