"""Marketing Ops report: saturation status, optimal vs current spend."""
from __future__ import annotations

from datetime import date

import pandas as pd

from agent_mmm.report.renderer import fmt_currency, save_report


def generate_mops_report(
    spec,
    diagnostics: dict,
    contributions_df: pd.DataFrame,
    roas_df: pd.DataFrame,
    optimize_result: dict | None = None,
) -> str:
    """Generate Marketing Ops markdown report.

    Returns the rendered markdown string.
    """
    currency = getattr(spec, "currency", "ILS")
    company = getattr(spec, "company", "")

    lines = [
        "# Marketing Operations Report",
        f"**{company}** | Generated {date.today().isoformat()}",
        "",
        "## Channel Investment Summary",
        "",
        "| Channel | Spend | Contribution | ROAS | Status |",
        "|---------|-------|--------------|------|--------|",
    ]

    hdi_low_col = [c for c in roas_df.columns if "hdi" in c and "low" in c] if roas_df is not None else []
    hdi_high_col = [c for c in roas_df.columns if "hdi" in c and "high" in c] if roas_df is not None else []

    total_spend = roas_df["spend_ils"].sum() if roas_df is not None and len(roas_df) > 0 else 0
    total_contrib = contributions_df["mean"].sum() if len(contributions_df) > 0 else 0

    if roas_df is not None and len(roas_df) > 0:
        median_roas = roas_df["roas_mean"].median()
        for _, row in roas_df.sort_values("roas_mean", ascending=False).iterrows():
            ch = row["channel"].replace("_spend", "")
            contrib_row = contributions_df[contributions_df["channel"] == row["channel"]]
            contrib = contrib_row["mean"].values[0] if len(contrib_row) > 0 else 0
            status = "above median" if row["roas_mean"] > median_roas else "below median"
            lines.append(
                f"| {ch} | {fmt_currency(row['spend_ils'], currency, 0)} "
                f"| {fmt_currency(contrib, currency, 0)} "
                f"| {row['roas_mean']:.2f}x | {status} |"
            )

    lines += ["", "## Saturation Notes", ""]
    lines.append(
        "Saturation analysis requires a fitted model with posterior predictive. "
        "Run `/mmm-attribute` then `/mmm-report` after fitting to populate this section."
    )
    lines.append("")

    if optimize_result is not None:
        lines += [
            "## Budget Reallocation Recommendation",
            "",
            f"Total budget: {fmt_currency(total_spend, currency, 0)}",
            "",
            "| Channel | Current | Optimal | Change |",
            "|---------|---------|---------|--------|",
        ]
        for ch, opt_spend in optimize_result.get("optimal_allocation", {}).items():
            curr = optimize_result["current_allocation"].get(ch, 0)
            delta = opt_spend - curr
            sign = "+" if delta >= 0 else ""
            lines.append(
                f"| {ch.replace('_spend','')} "
                f"| {fmt_currency(curr, currency, 0)} "
                f"| {fmt_currency(opt_spend, currency, 0)} "
                f"| {sign}{fmt_currency(delta, currency, 0)} |"
            )

        uplift = optimize_result.get("expected_uplift_mean", 0)
        lines.append(
            f"\nExpected contribution uplift from reallocation: **{fmt_currency(uplift, currency, 0)}**"
        )
        lines.append("")

    lines.append(f"_Report generated by agent_mmm. All monetary values in {currency}._")

    content = "\n".join(lines)
    save_report("mops", content)
    return content
