"""Marketing Ops report: saturation status, optimal vs current spend."""
from __future__ import annotations

from datetime import date

import pandas as pd

from agent_mmm.report.renderer import fmt_currency, save_report


def generate_mops_report(
    spec,
    diagnostics: dict,
    contributions_df: pd.DataFrame,
    effectiveness_df: pd.DataFrame,
    optimize_result: dict | None = None,
) -> str:
    """Generate Marketing Ops markdown report.

    `effectiveness_df` is the normalised output of compute_effectiveness().
    Returns the rendered markdown string.
    """
    currency = getattr(spec, "currency", "ILS")
    company = getattr(spec, "company", "")
    is_revenue = spec.target.type == "revenue"
    unit_name = spec.target.unit_name or ("unit" if not is_revenue else "")

    label = effectiveness_df["metric_label"].iloc[0] if effectiveness_df is not None and len(effectiveness_df) > 0 else ("ROAS" if is_revenue else "CPA")
    col_header = "ROAS" if is_revenue else label

    total_spend = effectiveness_df["spend_ils"].sum() if effectiveness_df is not None and len(effectiveness_df) > 0 else 0
    total_contrib = contributions_df["mean"].sum() if len(contributions_df) > 0 else 0

    lines = [
        "# Marketing Operations Report",
        f"**{company}** | Generated {date.today().isoformat()}",
        "",
        "## Channel Investment Summary",
        "",
        f"| Channel | Spend | Contribution | {col_header} | Status |",
        f"|---------|-------|--------------|{'—' * max(len(col_header), 4)}|--------|",
    ]

    if effectiveness_df is not None and len(effectiveness_df) > 0:
        median_val = effectiveness_df["metric_value_mean"].median()
        # For ROAS: higher = better (sort desc). For cost-per-unit: lower = better (sort asc).
        eff_sorted = effectiveness_df.sort_values("metric_value_mean", ascending=not is_revenue)
        for _, row in eff_sorted.iterrows():
            ch = row["channel"].replace("_spend", "")
            contrib_row = contributions_df[contributions_df["channel"] == row["channel"]]
            contrib = contrib_row["mean"].values[0] if len(contrib_row) > 0 else 0
            val = row["metric_value_mean"]

            if is_revenue:
                status = "above median" if val > median_val else "below median"
                val_fmt = f"{val:.2f}x"
                contrib_fmt = fmt_currency(contrib, currency, 0)
            else:
                status = "efficient" if val < median_val else "above median cost"
                val_fmt = f"{fmt_currency(val, currency, 0)}/{unit_name}"
                contrib_fmt = f"{contrib:,.0f} {unit_name}s"

            lines.append(
                f"| {ch} | {fmt_currency(row['spend_ils'], currency, 0)} "
                f"| {contrib_fmt} | {val_fmt} | {status} |"
            )

    lines += ["", "## Saturation Notes", ""]
    lines.append(
        "Saturation curves require a fitted model with posterior predictive. "
        "Run `/mmm-fit` then `/mmm-attribute` to populate saturation analysis."
    )
    lines.append("")

    if optimize_result is not None:
        lines += [
            "## Budget Reallocation Recommendation",
            "",
            f"Total budget: {fmt_currency(total_spend, currency, 0)}",
            "",
            "| Channel | Current | Optimal | Change |",
            "|---------|---------|---------|--------|",
        ]
        for ch, opt_spend in optimize_result.get("optimal_allocation", {}).items():
            curr = optimize_result["current_allocation"].get(ch, 0)
            delta = opt_spend - curr
            sign = "+" if delta >= 0 else ""
            lines.append(
                f"| {ch.replace('_spend','')} "
                f"| {fmt_currency(curr, currency, 0)} "
                f"| {fmt_currency(opt_spend, currency, 0)} "
                f"| {sign}{fmt_currency(delta, currency, 0)} |"
            )
        uplift = optimize_result.get("expected_uplift_mean", 0)
        lines.append(
            f"\nExpected contribution uplift from reallocation: **{fmt_currency(uplift, currency, 0)}**"
        )
        lines.append("")

    lines.append(f"_Report generated by agent_mmm. All monetary values in {currency}._")

    content = "\n".join(lines)
    save_report("mops", content)
    return content
